---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove the test containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: true
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Clear the instance config
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/instance_config.yml"
        state: absent
